# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: minichat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='minichat.proto',
  package='minichat',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eminichat.proto\x12\x08minichat\"\x07\n\x05\x45mpty\"V\n\x13Req_MessageToServer\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tfocusChan\x18\x02 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\x05\x12\x0f\n\x07message\x18\x04 \x01(\t\")\n\x08Req_User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tfocusChan\x18\x02 \x01(\t\"\'\n\x14Resp_MessageToClient\x12\x0f\n\x07message\x18\x01 \x01(\t\"#\n\x12Resp_AliveToClient\x12\r\n\x05\x61live\x18\x01 \x01(\x08\x32\xec\x01\n\x10mcServerServicer\x12\x45\n\rMessageStream\x12\x12.minichat.Req_User\x1a\x1e.minichat.Resp_MessageToClient0\x01\x12P\n\rCommandStream\x12\x1d.minichat.Req_MessageToServer\x1a\x1e.minichat.Resp_MessageToClient0\x01\x12?\n\x0b\x41liveSignal\x12\x12.minichat.Req_User\x1a\x1c.minichat.Resp_AliveToClientb\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='minichat.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=35,
)


_REQ_MESSAGETOSERVER = _descriptor.Descriptor(
  name='Req_MessageToServer',
  full_name='minichat.Req_MessageToServer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='minichat.Req_MessageToServer.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='focusChan', full_name='minichat.Req_MessageToServer.focusChan', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='command', full_name='minichat.Req_MessageToServer.command', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='minichat.Req_MessageToServer.message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=123,
)


_REQ_USER = _descriptor.Descriptor(
  name='Req_User',
  full_name='minichat.Req_User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='minichat.Req_User.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='focusChan', full_name='minichat.Req_User.focusChan', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=166,
)


_RESP_MESSAGETOCLIENT = _descriptor.Descriptor(
  name='Resp_MessageToClient',
  full_name='minichat.Resp_MessageToClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='minichat.Resp_MessageToClient.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=207,
)


_RESP_ALIVETOCLIENT = _descriptor.Descriptor(
  name='Resp_AliveToClient',
  full_name='minichat.Resp_AliveToClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='alive', full_name='minichat.Resp_AliveToClient.alive', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=244,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Req_MessageToServer'] = _REQ_MESSAGETOSERVER
DESCRIPTOR.message_types_by_name['Req_User'] = _REQ_USER
DESCRIPTOR.message_types_by_name['Resp_MessageToClient'] = _RESP_MESSAGETOCLIENT
DESCRIPTOR.message_types_by_name['Resp_AliveToClient'] = _RESP_ALIVETOCLIENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'minichat_pb2'
  # @@protoc_insertion_point(class_scope:minichat.Empty)
  })
_sym_db.RegisterMessage(Empty)

Req_MessageToServer = _reflection.GeneratedProtocolMessageType('Req_MessageToServer', (_message.Message,), {
  'DESCRIPTOR' : _REQ_MESSAGETOSERVER,
  '__module__' : 'minichat_pb2'
  # @@protoc_insertion_point(class_scope:minichat.Req_MessageToServer)
  })
_sym_db.RegisterMessage(Req_MessageToServer)

Req_User = _reflection.GeneratedProtocolMessageType('Req_User', (_message.Message,), {
  'DESCRIPTOR' : _REQ_USER,
  '__module__' : 'minichat_pb2'
  # @@protoc_insertion_point(class_scope:minichat.Req_User)
  })
_sym_db.RegisterMessage(Req_User)

Resp_MessageToClient = _reflection.GeneratedProtocolMessageType('Resp_MessageToClient', (_message.Message,), {
  'DESCRIPTOR' : _RESP_MESSAGETOCLIENT,
  '__module__' : 'minichat_pb2'
  # @@protoc_insertion_point(class_scope:minichat.Resp_MessageToClient)
  })
_sym_db.RegisterMessage(Resp_MessageToClient)

Resp_AliveToClient = _reflection.GeneratedProtocolMessageType('Resp_AliveToClient', (_message.Message,), {
  'DESCRIPTOR' : _RESP_ALIVETOCLIENT,
  '__module__' : 'minichat_pb2'
  # @@protoc_insertion_point(class_scope:minichat.Resp_AliveToClient)
  })
_sym_db.RegisterMessage(Resp_AliveToClient)



_MCSERVERSERVICER = _descriptor.ServiceDescriptor(
  name='mcServerServicer',
  full_name='minichat.mcServerServicer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=247,
  serialized_end=483,
  methods=[
  _descriptor.MethodDescriptor(
    name='MessageStream',
    full_name='minichat.mcServerServicer.MessageStream',
    index=0,
    containing_service=None,
    input_type=_REQ_USER,
    output_type=_RESP_MESSAGETOCLIENT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CommandStream',
    full_name='minichat.mcServerServicer.CommandStream',
    index=1,
    containing_service=None,
    input_type=_REQ_MESSAGETOSERVER,
    output_type=_RESP_MESSAGETOCLIENT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AliveSignal',
    full_name='minichat.mcServerServicer.AliveSignal',
    index=2,
    containing_service=None,
    input_type=_REQ_USER,
    output_type=_RESP_ALIVETOCLIENT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MCSERVERSERVICER)

DESCRIPTOR.services_by_name['mcServerServicer'] = _MCSERVERSERVICER

# @@protoc_insertion_point(module_scope)
